const LoadingSpinner=()=>
{
  return  <div className="d-flex justify-content-center spinner ">
  <div className="spinner-border" role="status" style={{width:"7rem",height:"7rem"}}>
    <span className="visually-hidden ">Loading...fsadjkfds kffskslk;jkfj as Lorem ipsum dolor sit, amet consectetur adipisicing elit. Reiciendis nisi corporis consequuntur fugit molestias sequi perferendis voluptates! Voluptate et necessitatibus sed reprehenderit provident! Sapiente impedit quasi recusandae, corrupti aliquam animi, cupiditate laborum aut corporis aperiam incidunt harum mollitia ea quos in quidem nisi dolores provident sequi fugiat velit sint ducimus nulla? Explicabo molestias maxime totam quaerat. Quo voluptatem sunt accusamus! Sed officiis asperiores nisi in ratione adipisci consectetur vel voluptatum, quasi consequatur ipsum autem, corporis nobis architecto distinctio laboriosam dolorem labore quam atque maxime doloribus velit perspiciatis. Quibusdam quas doloremque delectus nisi repellat! Voluptate veniam unde vitae ipsa dolorem dolore nobis? Vero ipsa consectetur ducimus. Voluptatibus porro, iusto quia quae molestias ab non commodi voluptas voluptatem architecto accusantium ut cupiditate, inventore nobis deserunt aliquid numquam aspernatur ullam. Distinctio natus dolor modi repudiandae laudantium tempora repellendus doloremque cumque corrupti nulla possimus iusto repellat corporis culpa, ut harum saepe, blanditiis esse explicabo mollitia. Minima voluptatum sequi atque soluta obcaecati veniam tenetur, at quia ea rem velit mollitia hic perspiciatis facere deleniti ratione, quam magnam dignissimos voluptate enim quae officiis. Et officia incidunt, quisquam quasi est alias, officiis, laboriosam sed impedit dolore ipsum voluptatum veniam. Facilis commodi nulla vel modi. Eum, molestiae? Maiores necessitatibus dignissimos ducimus reprehenderit sequi tempora itaque pariatur tenetur, cum officiis maxime? Adipisci ipsam totam enim porro. Illum autem qui, tenetur possimus culpa eveniet a magnam consequatur. Veritatis magni nisi optio consectetur nostrum quas expedita sapiente, placeat mollitia illum a sequi repellat doloremque rem maiores repudiandae assumenda rerum beatae deleniti modi necessitatibus? Est ut repudiandae libero vero quasi similique ex, accusantium veritatis dolorem cum, voluptatum sed iure nemo recusandae molestias. Deserunt aliquam sunt sit, possimus animi dolorem dolor beatae iste, omnis quibusdam ducimus minima error nemo facere magnam molestiae adipisci provident accusamus inventore autem dolores quos. Consequuntur veniam beatae quibusdam, dolores cumque saepe excepturi voluptatum reprehenderit in sequi ad sapiente omnis totam non. Consectetur quidem deserunt at repudiandae voluptas. Fugit magni, iste sunt necessitatibus praesentium minima iusto expedita dolores ad distinctio quaerat consequuntur deleniti sed alias nesciunt obcaecati voluptate ea doloribus quod!</span>
  </div>
</div>
}

export default LoadingSpinner